<?php
/*
+--------------------------------------------------------------------------
|
|	WARNING: REMOVING THIS COPYRIGHT HEADER IS EXPRESSLY FORBIDDEN
|
|   ECardMax Version 10.5
|   ========================================
|   (c) 1999 - 2016 ECARDMAX.COM - All right reserved 
|	Software For Website, Inc.
|   http://www.ecardmax.com 
|   ========================================
|   Email: webmaster@ecardmax.com
|   Purchase Info: http://www.ecardmax.com/purchase/
|   Request Installation: http://ecardmax.com/ehelpmax/
|	
|	WARNING //--------------------------
|
|	Selling the code for this program without prior written consent is expressly forbidden. 
|	This computer program is protected by copyright law. 
|	Unauthorized reproduction or distribution of this program, or any portion of if,
|	may result in severe civil and criminal penalties and will be prosecuted to 
|	the maximum extent possible under the law.
+--------------------------------------------------------------------------
*/	
	if(ECARDMAX!=1)exit;
	if ($admin_login != $crypt_pass){
		//Show login page
		print get_html_from_layout("admin/html/show_login.html");
		exit;
	}

	if($what=="edit_me_admin_config"){
		if (!$exist = get_dbvalue($table,$edit_id,"$edit_id='$edit_id_value'")) {
			$field_name = "(config_name,config_value)";
			$field_value = "('$edit_id_value','$edit_value')";
			insert_data_to_db("$table",$field_name,$field_value);
		} else {
			update_field_in_db("$table","$edit_key",$edit_value,"$edit_id='$edit_id_value' LIMIT 1");
		}
		
		//Build file config2.php
		set_global_var_config("max_config");
		$cg ="<?php\n\n\t//DO NOT EDIT THIS FILE. USE ADMIN TO MAKE CHANGE\n\n";
		foreach($http_vars as $key=>$val){		
			if(!(strpos($key,"cf_")===false)){ //if true
				$val=str_replace("\"","&quot;",$val);
				$cg .="\t" . "\$$key = \"$val\"; \n";
			}
		}
		$cg .="?>";
		set_file_content("$ecard_root/config2.php",$cg);		
	}
	else{
		set_global_var_config("max_config");
		//Selected for DropDown Menu
		foreach($http_vars as $key=>$val){
			set_global_var("selected_". $key ."_" . $val,"selected=\"selected\"");
			set_global_var("checked_". $key ."_" . $val,"checked=\"checked\"");
		}
		
		//Set default template
		$list_dir_template=get_list_dir("$ecard_root/templates");
		$set_template="<select size=\"1\" id=\"set_template\" onchange=\"Editme('index.php?step=admin_system_config&what=edit_me_admin_config&table=max_config&edit_id=config_name&edit_id_value=cf_set_template&edit_key=config_value&edit_value=',this.value,'1',1,this.id);\">";
		foreach($list_dir_template as $template){
			if($template==$cf_set_template){
				$set_template.="<option value=\"$template\" selected=\"selected\">$template</option>";
			}
			else{
				$set_template.="<option value=\"$template\">$template</option>";
			}
		}
		$set_template.="</select>";
		
		//Set default language
		$list_lang_file=get_list_file("$ecard_root/languages","_lang.php$");
		$set_default_language="<select size=\"1\" id=\"set_language\" onchange=\"Editme('index.php?step=admin_system_config&what=edit_me_admin_config&table=max_config&edit_id=config_name&edit_id_value=cf_language&edit_key=config_value&edit_value=',this.value,'1',1,this.id);\">";
		foreach($list_lang_file as $mylang){
			$lang_name_display=ucwords(str_replace("_lang.php","",$mylang));
			if($mylang==$cf_language){
				$set_default_language.="<option value=\"$mylang\" selected=\"selected\">$lang_name_display</option>";
			}
			else{
				$set_default_language.="<option value=\"$mylang\">$lang_name_display</option>";
			}
		}
		$set_template.="</select>";
		
		// Set default currency symbol
		$currency_symbols = array(
			"$" => "$ US",
			"£" => "£ English",
			"€" => "€ Euro",
			"¥" => "¥ Japanese",
			"₣" => "₣ French",
			"Đ" => "Đ Vietnamese",
			"₩" => "₩ Korean",
		);
		$set_default_currency_symbol = "<select name=\"cf_currecy\" size=\"1\" id=\"cf_currecy\" onFocus=\"original_value=this.value;\" onChange=\"Editme('index.php?step=admin_system_config&what=edit_me_admin_config&table=max_config&edit_id=config_name&edit_id_value=cf_currecy&edit_key=config_value&edit_value=',this.value,'1',original_value,this.id);\">";
		foreach ($currency_symbols as $key => $value) {
			if ($key==$cf_currecy) {
				$set_default_currency_symbol .= "<option value=\"$key\" selected>$value</option>";
			}
			else {
				$set_default_currency_symbol .= "<option value=\"$key\">$value</option>";
			}			
		}
		$set_default_currency_symbol .= "</select>";
		
		// Get card category
		$facebook_card_specified_category="<select name=\"cf_fb_card_specified_category\" size=\"1\" id=\"cf_fb_card_specified_category\" onfocus=\"original_value=this.value;\" onchange=\"Editme('index.php?step=admin_system_config&what=edit_me_admin_config&table=max_config&edit_id=config_name&edit_id_value=cf_fb_card_specified_category&edit_key=config_value&edit_value=',this.value,'1',original_value,this.id);\">";
		$list_data=set_array_from_query("max_category","*","cat_parent='' Order by cat_order,cat_name_display");
		$xorder=0;
		foreach($list_data as $row_data){
			$val = $row_data[cat_id] ;
			
			if ($cf_fb_card_specified_category==$val) {
				$facebook_card_specified_category .= "<option value=\"$val\" selected>$row_data[cat_name_display]</option>";
			}
			else {
				$facebook_card_specified_category .= "<option value=\"$val\">$row_data[cat_name_display]</option>";
			}
			
			$cat_row=get_row("max_category","*","cat_id='$val'");
			$list_data_1=set_array_from_query("max_category","*","cat_parent='$cat_row[cat_dir]' Order by cat_order,cat_name_display");
			foreach($list_data_1 as $row_data_1){
				$val_1 = $row_data_1[cat_id] ;
				
				if ($cf_fb_card_specified_category==$val_1) {
					$facebook_card_specified_category .= "<option value=\"$val_1\" selected>$row_data_1[cat_name_display]</option>";
				}
				else {
					$facebook_card_specified_category .= "<option value=\"$val_1\">$row_data_1[cat_name_display]</option>";
				}
			}
		}
		$facebook_card_specified_category .= "</select>";

		//Show local time
		$show_local_time=DateFormat($gmt_timestamp_now);
		//server_time_zone
		$server_time_zone=array();
		$server_time_zone[0]=array('value'=>"-12.00",'text'=>"(GMT-12:00) International Date Line West");
		$server_time_zone[1]=array('value'=>"-11.00",'text'=>"(GMT-11:00) Midway Island, Samoa");
		$server_time_zone[2]=array('value'=>"-10.00",'text'=>"(GMT-10:00) Hawaii");
		$server_time_zone[3]=array('value'=>"-9.00",'text'=>"(GMT-9:00) Alaska");
		$server_time_zone[4]=array('value'=>"-8.00",'text'=>"(GMT-8:00) Pacific Time (US &amp; Canada)");
		$server_time_zone[5]=array('value'=>"-7.00",'text'=>"(GMT-7:00) Arizona, Chihuahua, La Paz, Mazzatlan");
		$server_time_zone[6]=array('value'=>"-7.00",'text'=>"(GMT-7:00) Mountain Time (US &amp; Canada)");
		$server_time_zone[7]=array('value'=>"-6.00",'text'=>"(GMT-6:00) Central America");
		$server_time_zone[8]=array('value'=>"-6.00",'text'=>"(GMT-6:00) Central Time (US &amp; Canada)");
		$server_time_zone[9]=array('value'=>"-6.00",'text'=>"(GMT-6:00) Guadalajara, Mexico City, Monterrey");
		$server_time_zone[10]=array('value'=>"-6.00",'text'=>"(GMT-6:00) Saskatchewan");
		$server_time_zone[11]=array('value'=>"-5.00",'text'=>"(GMT-5:00) Bogota, Lima, Quito");
		$server_time_zone[12]=array('value'=>"-5.00",'text'=>"(GMT-5:00) Eastern Time (US &amp; Canada)");
		$server_time_zone[13]=array('value'=>"-5.00",'text'=>"(GMT-5:00) Indiana (East)");
		$server_time_zone[14]=array('value'=>"-4.00",'text'=>"(GMT-4:00) Atlantic Time (Canada)");
		$server_time_zone[15]=array('value'=>"-4.00",'text'=>"(GMT-4:00) Caracas, La Paz, Santiago");
		$server_time_zone[16]=array('value'=>"-3.50",'text'=>"(GMT-3:30) Newfoundland");
		$server_time_zone[17]=array('value'=>"-3.00",'text'=>"(GMT-3:00) Brasilia, Greenland, Buenos Aires ");
		$server_time_zone[18]=array('value'=>"-2.00",'text'=>"(GMT-2:00) Mid-Atlantic");
		$server_time_zone[19]=array('value'=>"-1.00",'text'=>"(GMT-1:00) Azores, Cape Verde Is.");
		$server_time_zone[20]=array('value'=>"0.00",'text'=>"(GMT) Greenwich Mean Time");
		$server_time_zone[21]=array('value'=>"0.00",'text'=>"(GMT) Casablanca, Monrovia");
		$server_time_zone[22]=array('value'=>"0.00",'text'=>"(GMT) Dublin, Edinburgh, Lisbon, London");
		$server_time_zone[23]=array('value'=>"+1.00",'text'=>"(GMT+1:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna");
		$server_time_zone[24]=array('value'=>"+1.00",'text'=>"(GMT+1:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague");
		$server_time_zone[25]=array('value'=>"+1.00",'text'=>"(GMT+1:00) Brussels, Copenhagen, Madrid, Paris");
		$server_time_zone[26]=array('value'=>"+1.00",'text'=>"(GMT+1:00) Sarajevo, Skopje, Warsaw, Zagreb");
		$server_time_zone[27]=array('value'=>"+1.00",'text'=>"(GMT+1:00) West Central Africa");
		$server_time_zone[28]=array('value'=>"+2.00",'text'=>"(GMT+2:00) Athens, Beirut, Istanbul, Minsk, Jerusalem");
		$server_time_zone[29]=array('value'=>"+2.00",'text'=>"(GMT+2:00) Bucharest, Cairo, Harare, Pretoria");
		$server_time_zone[30]=array('value'=>"+2.00",'text'=>"(GMT+2:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius");
		$server_time_zone[31]=array('value'=>"+3.00",'text'=>"(GMT+3:00) Baghdad, Kuwait, Riyadh, Nairobi, Tehran");
		$server_time_zone[32]=array('value'=>"+3.00",'text'=>"(GMT+3:00) Moscow, St. Petersburg, Volgograd");
		$server_time_zone[33]=array('value'=>"+3.50",'text'=>"(GMT+3:30) Tehran");
		$server_time_zone[34]=array('value'=>"+4.00",'text'=>"(GMT+4:00) Abu Dhabi, Muscat, Baku, Tbilisi, Yerevan");
		$server_time_zone[35]=array('value'=>"+4.50",'text'=>"(GMT+4:30) Kabul");
		$server_time_zone[36]=array('value'=>"+5.00",'text'=>"(GMT+5:00) Ekaterinburg, Islamabad, Karachi, Tashkent");
		$server_time_zone[37]=array('value'=>"+5.50",'text'=>"(GMT+5:30) Chennai, Kolkata, Mumbai, New Delhi");
		$server_time_zone[38]=array('value'=>"+5.75",'text'=>"(GMT+5:45) Kathmandu");
		$server_time_zone[39]=array('value'=>"+6.00",'text'=>"(GMT+6:00) Almaty, Novosibirsk, Astana, Dhaka");
		$server_time_zone[40]=array('value'=>"+6.50",'text'=>"(GMT+6:30) Rangoon");
		$server_time_zone[41]=array('value'=>"+7.00",'text'=>"(GMT+7:00) Bangkok, Hanoi, Jakarta, Krasnoyarsk");
		$server_time_zone[42]=array('value'=>"+8.00",'text'=>"(GMT+8:00) Beijing, Chongqing, Hong Kong, Urumqi");
		$server_time_zone[43]=array('value'=>"+8.00",'text'=>"(GMT+8:00) Irkutsk, Ulaan Bataar, Kuala Lumpur, Singapore");
		$server_time_zone[44]=array('value'=>"+8.00",'text'=>"(GMT+8:00) Perth, Taipei");
		$server_time_zone[45]=array('value'=>"+9.00",'text'=>"(GMT+9:00) Osaka, Sapporo, Tokyo, Seoul, Yakutsk");
		$server_time_zone[46]=array('value'=>"+9.50",'text'=>"(GMT+9:30) Adelaide, Darwin");
		$server_time_zone[47]=array('value'=>"+10.00",'text'=>"(GMT+10:00) Brisbane, Canberra, Melbourne, Sydney");
		$server_time_zone[48]=array('value'=>"+10.00",'text'=>"(GMT+10:00) Guam, Port Moresby, Hobart, Vladivostok");
		$server_time_zone[49]=array('value'=>"+11.00",'text'=>"(GMT+11:00) Magadan, Solomon Is., New Caledonia");
		$server_time_zone[50]=array('value'=>"+12.00",'text'=>"(GMT+12:00) Auckland, Wellington, Fiji, Kamchatka, Marshall Is.");
		$server_time_zone[51]=array('value'=>"+13.00",'text'=>"(GMT+13:00) Nuku'alofa");
		$list_option="";
		foreach($server_time_zone as $timezone)
		{
			if($cf_timezone==$timezone[value])
			{
				$list_option.="<option value=\"$timezone[value]\" selected=\"selected\">(GMT".$timezone[value].")</option>";
			}
			else
				$list_option.="<option value=\"$timezone[value]\">$timezone[text]</option>";	
		}
		//var_dump($list_option);
		// Get RewriteBase
		$RewriteBase = get_RewriteBase();
		$system_config_txt_search_engine_friendly_url_note=str_replace("%RewriteBase%","$RewriteBase",$system_config_txt_search_engine_friendly_url_note);
		$system_config_txt_use_easy_edit_template_feature=str_replace("%ecard_url%","$ecard_url",$system_config_txt_use_easy_edit_template_feature);
		$system_config_txt_path_to_your_watermark_image=str_replace("%ecard_url%","$ecard_url",$system_config_txt_path_to_your_watermark_image);
		$system_config_txt_enable_twitter_note=str_replace("%php_version%",phpversion(),$system_config_txt_enable_twitter_note);
		
		// Get GD info
		$gd_info='<div style="margin: 10px;">';
		$gd_info.='<p style="color: #444444; font-size: 130%;">GD is ';
		if (function_exists("gd_info")) {
			$gd_info.='<span style="color: #00AA00; font-weight: bold;">supported</span> by your server!</p>';
			$gd = gd_info();
			foreach ($gd as $k => $v) {
				$gd_info.='<div style="width: 340px; border-bottom: 1px solid #DDDDDD; padding: 2px;">';
				$gd_info.='<span style="float: left;width: 300px;">' . $k . '</span> ';
				if ($v)
					$gd_info.='<span style="color: #00AA00; font-weight: bold;">Yes</span>';
				else
					$gd_info.='<span style="color: #EE0000; font-weight: bold;">No</span>';
					
				$gd_info.='<div style="clear:both;"><!-- --></div></div>';
			}
		}
		else {
			$gd_info.='<span style="color: #EE0000; font-weight: bold;">not supported</span> by your server!</p>';
		}
		$gd_info.='</div>';

		set_global_var("print_object",get_html_from_layout("admin/html/admin_system_config.html"));
		print_admin_header_footer_page();
		exit;
	}
	
	//--------------------------------------------------------------------------------
	//Get eCard Rewrite Base
	function get_RewriteBase() {
		$RewriteBase = str_replace("/admin/index.php","",$_SERVER["PHP_SELF"]);
		
		return $RewriteBase;
	}
?>