<?php
/*
+--------------------------------------------------------------------------
|
|	WARNING: REMOVING THIS COPYRIGHT HEADER IS EXPRESSLY FORBIDDEN
|
|   ECardMax Version 10.5
|   ========================================
|   (c) 1999 - 2016 ECARDMAX.COM - All right reserved 
|	Software For Website, Inc.
|   http://www.ecardmax.com 
|   ========================================
|   Email: webmaster@ecardmax.com
|   Purchase Info: http://www.ecardmax.com/purchase/
|   Request Installation: http://ecardmax.com/ehelpmax/
|	
|	WARNING //--------------------------
|
|	Selling the code for this program without prior written consent is expressly forbidden. 
|	This computer program is protected by copyright law. 
|	Unauthorized reproduction or distribution of this program, or any portion of if,
|	may result in severe civil and criminal penalties and will be prosecuted to 
|	the maximum extent possible under the law.
+--------------------------------------------------------------------------
*/	
	if(ECARDMAX!=1)exit;
	if ($admin_login != $crypt_pass){
		//Show login page
		print get_html_from_layout("admin/html/show_login.html");
		exit;
	}	
	
	//Auto add new skin to database if found
	$list_dir_database=get_dblistvalue("max_skin","skin_dirname");
	$list_dir=get_list_dir("$ecard_root/resource/skin");
	$db_change ="";
	$skin_order=1000;
	foreach($list_dir as $dir){
		if (!in_array($dir, $list_dir_database)){
			//Insert new skin to database
			$skin_order++;
			$skin_text_color=get_file_content("$ecard_root/resource/skin/$dir/color.txt");
			if($skin_text_color=="")$skin_text_color="BLACK";
			$skin_name_display=str_replace("_"," ",$dir);
			$field_name ="(skin_name_display,skin_dirname,skin_text_color,skin_order,skin_active)";
			$field_value ="('$skin_name_display','$dir','$skin_text_color',$skin_order,1)";
			insert_data_to_db("max_skin",$field_name,$field_value);
			$db_change ="1";
		}
	}

	//Auto remove skin from mysql if it's not found on server
	foreach($list_dir_database as $dir_mysql){
		if (!in_array($dir_mysql, $list_dir)){
			//Remove from database
			delete_row("max_skin","skin_dirname='$dir_mysql'");
			$db_change ="1";
		}
	}	

	if($db_change=="1")RefreshSortOrder();

	if($what=="add_new"){		
		if (!is_writable("$ecard_root/resource/skin")){
			$skin_message_you_must_chmod_this_folder=str_replace("%skin_folder%","$ecard_root/resource/skin",$skin_message_you_must_chmod_this_folder);
			$show_info="$skin_message_you_must_chmod_this_folder";
		}
		else{
			$skin_order=get_dbvalue("max_skin","count(skin_id)","skin_id<>''");

			//Auto remove spcial character for skin_dirname (this a folder)
			$skin_dirname = ereg_replace( "[^A-Za-z0-9]", "", $skin_name_display);	
			$upload_to = "$ecard_root/resource/skin/$skin_dirname";

			//Create folder $skin_dirname
			if(file_exists($upload_to)){
				$rand_num = substr(md5(uniqid(rand(),1)), 0, 8);
				$upload_to = $upload_to . $rand_num;
				$skin_dirname = $skin_dirname . $rand_num;
			}

			mkdir ($upload_to, 0777); 
			chmod ($upload_to, 0777);

			if (file_exists($upload_to)){
				//Upload image
				for ($i=1;$i<=7;$i++){
					$file_key = "file$i";
					$file_upload_name = $POST_FILES[$file_key]['name'];	
					move_uploaded_file($POST_FILES[$file_key]['tmp_name'], "$upload_to/$file_upload_name");
					chmod("$upload_to/$file_upload_name",0777);
				}			

				//Insert to database table max_skin
				$skin_order++;
				$field_name ="(skin_name_display,skin_dirname,skin_active,skin_text_color,skin_order)";
				$field_value ="('$skin_name_display','$skin_dirname',1,'$skin_text_color',$skin_order)";
				insert_data_to_db("max_skin",$field_name,$field_value);
				$skin_name_display = stripslashes($skin_name_display);
				$skin_message_skin_has_been_added=str_replace("%skin_name_display%",$skin_name_display,$skin_message_skin_has_been_added);
				$show_info ="<span class=OK_Message>Skin name $skin_name_display has been added</span><br />\n";
			}
		}		
	}
	elseif($what=="edit_me_admin_config"){
		update_field_in_db("$table","$edit_key",$edit_value,"$edit_id='$edit_id_value' LIMIT 1");
		/*
		//Build file config2.php
		set_global_var_config("max_config");
		$cg ="<?php\n\n\t//DO NOT EDIT THIS FILE. USE ADMIN TO MAKE CHANGE\n\n";
		foreach($http_vars as $key=>$val){		
			if(!(strpos($key,"cf_")===false)){ //if true
				$val=str_replace("\"","&quot;",$val);
				$cg .="\t" . "\$$key = \"$val\"; \n";
			}
		}
		$cg .="?>";
		set_file_content("$ecard_root/config2.php",$cg);
		*/
	}
	elseif($what=="delete_selected"){
		foreach($http_vars as $key=>$val){
			if(!(strpos($key,"mylist_id")===false)){ //if true
				$selected_id =str_replace("mylist_id","",$key);
				//Delete files & folder
				$skin_dirname=get_dbvalue("max_skin","skin_dirname","skin_id='$selected_id'");
								
				if (is_writable("$ecard_root/resource/skin/$skin_dirname")){
					$array=get_list_file("$ecard_root/resource/skin/$skin_dirname");
					$wrong="";
					foreach($array as $file){
						if (is_writable("$ecard_root/resource/skin/$skin_dirname/$file")){
							@unlink("$ecard_root/resource/skin/$skin_dirname/$file");
						}
						else{
							$wrong = 1;
							$skin_message_cannt_delete_file_permission_denied=str_replace("%file%","$ecard_root/resource/skin/$skin_dirname/$file",$skin_message_cannt_delete_file_permission_denied);
							$show_info .="$skin_message_cannt_delete_file_permission_denied<br />\n";
						}
					}
					if($wrong ==""){
						@rmdir("$ecard_root/resource/skin/$skin_dirname");
						$skin_message_skin_has_been_removed=str_replace("%skin_dirname%","$skin_dirname",$skin_message_skin_has_been_removed);
						$show_info .="<span class=\"OK_Message\">$skin_message_skin_has_been_removed</span><br />\n";
					}
					else{
						$skin_message_cannt_delete_folder_skin_permission_denied=str_replace("%skin_dirname%","$ecard_root/resource/skin/$skin_dirname",$skin_message_cannt_delete_folder_skin_permission_denied);
						$show_info .="$skin_message_cannt_delete_folder_skin_permission_denied<br />\n";
					}
				}
				else{
					$skin_message_cannt_delete_folder_skin_permission_denied=str_replace("%skin_dirname%","$ecard_root/resource/skin/$skin_dirname",$skin_message_cannt_delete_folder_skin_permission_denied);
					$show_info .="$skin_message_cannt_delete_folder_skin_permission_denied<br />\n";
				}

				//Delete row in database
				delete_row("max_skin","skin_id='$selected_id' LIMIT 1");
			}
		}
		RefreshSortOrder();
	}
	elseif($what=="set_sort_order"){
		$list_sort=set_array_from_query("max_skin","skin_id,skin_order","skin_id<>'' Order by skin_order,skin_name_display");		
		foreach($list_sort as $array_sort){
			if($current_sort > $sort_number){
				if($array_sort[skin_order]>=$sort_number){			
					update_field_in_db("max_skin","skin_order",$array_sort[skin_order]+1,"skin_id='$array_sort[skin_id]' LIMIT 1");
				}
			}
			else{
				if($array_sort[skin_order]<=$sort_number){			
					update_field_in_db("max_skin","skin_order",$array_sort[skin_order]-1,"skin_id='$array_sort[skin_id]' LIMIT 1");
				}
			}
		}		
		update_field_in_db("max_skin","skin_order",$sort_number,"skin_id='$skin_id' LIMIT 1");
		
		RefreshSortOrder();
		$what="";
		set_global_var("what","");
	}

	if($row_number =="" || $row_number =="0" || !is_numeric($row_number)) $row_number = 15;
	set_global_var("row_number",$row_number);
	$row_per_page = $row_number;
				
	if ($page < 1 || $page=="") $page =1;
	$start = ($page-1)* 1 * $row_per_page;
	$end = $start + 1 * $row_per_page;

	$list_data =set_array_from_query("max_skin","*","skin_id<>'' Order by skin_order,skin_name_display LIMIT $start,$row_per_page");
	$count_list=get_dbvalue("max_skin","count(skin_id)");

	if ($end > $count_list) $end = $count_list;
	$show_list_table="";
	$xrow=0;
	for ($z=$start; $z<$end; $z++) {
		$val = $list_data[$xrow][skin_id] ;
		$row_data=$list_data[$xrow];

		//Show sort order dropdown menu
		$show_sort="<select size=\"1\" name=\"skin_order$val\" id=\"skin_order$val\" onchange=\"location.href='index.php?step=$step&what=set_sort_order&skin_id=$val&current_sort=$row_data[skin_order]&sort_number='+this.value;\">";
		for($i=1;$i<=$count_list;$i++){
			if($row_data[skin_order]==$i){
				$show_sort.="<option value=\"$i\" selected=\"selected\">$i</option>\n";
			}
			else{
				$show_sort.="<option value=\"$i\" >$i</option>\n";
			}
		}
		$show_sort.="</select>";

		//Show icon
		if(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/skin.gif")){
			$show_icon ="<img border=\"1\" src=\"$ecard_url/resource/skin/$row_data[skin_dirname]/skin.gif\" alt=\"\" />";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/skin.jpg")){
			$show_icon ="<img border=\"1\" src=\"$ecard_url/resource/skin/$row_data[skin_dirname]/skin.jpg\" alt=\"\" />";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/skin.png")){
			$show_icon ="<img border=\"1\" src=\"$ecard_url/resource/skin/$row_data[skin_dirname]/skin.png\" alt=\"\" />";
		}
		else{
			$show_icon ="<div style=\"border:1px solid black;background-color:red;width:73px;height:84px;text-align:center;color:yellow;font-weight:bold\">$skin_txt_no_icon</div>";
		}

		//Show title
		$show_title="<input id=\"skin_name_display$val\" title=\"$skin_tooltip_click_here_to_rename\" type=\"text\" value=\"$row_data[skin_name_display]\" style=\"border:0px;background-color:#EAEAEA;cursor:pointer;width:220px;text-decoration:underline;\" onfocus=\"original_value=this.value;this.style.border='1px solid silver';this.style.textDecoration='none';this.style.cursor='text';\" onblur=\"this.style.border='0px';this.style.textDecoration='underline';this.style.cursor='pointer';\" onchange=\"Editme('index.php?step=edit_me&table=max_skin&edit_id=skin_id&edit_id_value=$val&edit_key=skin_name_display&edit_value=',this.value,'1',original_value,this.id);\" />";		
		
		//Show text color
		if($row_data[skin_text_color]==""){
			$get_skin_text_color=get_file_content("$ecard_root/resource/skin/$row_data[skin_dirname]/color.txt");
			if($get_skin_text_color=="")$get_skin_text_color="black";
			$get_skin_text_color=strtoupper($get_skin_text_color);
			update_field_in_db("max_skin","skin_text_color",$get_skin_text_color,"skin_id='$val' LIMIT 1");			
		}
		else{
			$get_skin_text_color=$row_data[skin_text_color];
		}
		$get_skin_text_color=strtoupper($get_skin_text_color);
		$show_text_color ="<div style=\"float:left\"><input style=\"width:70px\" id=\"skin_text_color$val\" type=\"text\" value=\"$get_skin_text_color\"  onfocus=\"original_value=this.value;\"  onchange=\"Editme('index.php?step=edit_me&table=max_skin&edit_id=skin_id&edit_id_value=$val&edit_key=skin_text_color&edit_value=',this.value,'1',original_value,this.id);\" /></div> <div style=\"float:left;width:13px;height:13px;background-color:$get_skin_text_color;border:1px solid silver;cursor:pointer;\" id=\"span_skin_text_color$val\" title=\"$skin_tooltip_click_to_open_color_picker\" onclick=\"skin_id=$val;ShowDiv(this.id,'color_table',0,0);\"></div>";

		//Show preview icon
		if(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bar.gif")){
			$bar="bar.gif";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bar.jpg")){
			$bar="bar.jpg";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bar.png")){
			$bar="bar.png";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bar.swf")){
			$bar="bar.swf";
		}
		list($barW,$barH)=getimagesize("$ecard_root/resource/skin/$row_data[skin_dirname]/$bar");

		if(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bkg.gif")){
			$bkg="bkg.gif";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bkg.jpg")){
			$bkg="bkg.jpg";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bkg.png")){
			$bkg="bkg.png";
		}

		if(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bottom.gif")){
			$bottom="bottom.gif";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bottom.jpg")){
			$bottom="bottom.jpg";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bottom.png")){
			$bottom="bottom.png";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/bottom.swf")){
			$bottom="bottom.swf";
		}
		list($bottomW,$bottomH)=getimagesize("$ecard_root/resource/skin/$row_data[skin_dirname]/$bottom");

		if(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/icon.gif")){
			$icon="icon.gif";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/icon.jpg")){
			$icon="icon.jpg";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/icon.png")){
			$icon="icon.png";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/icon.swf")){
			$icon="icon.swf";
		}
		list($iconW,$iconH)=getimagesize("$ecard_root/resource/skin/$row_data[skin_dirname]/$icon");

		if(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/top.gif")){
			$top="top.gif";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/top.jpg")){
			$top="top.jpg";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/top.png")){
			$top="top.png";
		}
		elseif(file_exists("$ecard_root/resource/skin/$row_data[skin_dirname]/top.swf")){
			$top="top.swf";
		}
		list($topW,$topH)=getimagesize("$ecard_root/resource/skin/$row_data[skin_dirname]/$top");
		
		$show_preview_icon="<img border=\"0\" src=\"html/07_icon_search_keyword.gif\" alt=\"\" style=\"cursor:pointer\" onclick=\"skin_id=$val;HideItAll();document.getElementById('print_my_title').innerHTML=document.getElementById('skin_name_display$val').value;document.getElementById('cell$val').style.backgroundColor='#FAEDC8';document.getElementById('cell$val').style.border='thick solid #FCAA03';document.getElementById('preview_cell$val').style.backgroundColor='#FAEDC8';document.getElementById('preview_cell$val').style.border='thick solid #FCAA03';Previewskin('$ecard_url/resource/skin/$row_data[skin_dirname]/$bar,$barW,$barH','$ecard_url/resource/skin/$row_data[skin_dirname]/$bkg','$ecard_url/resource/skin/$row_data[skin_dirname]/$bottom,$bottomW,$bottomH','$ecard_url/resource/skin/$row_data[skin_dirname]/$icon,$iconW,$iconH','$ecard_url/resource/skin/$row_data[skin_dirname]/$top,$topW,$topH');\" />";

		//Show on/off checkbox
		if($row_data[skin_active]=="1"){
			$checked_it ="checked=\"checked\"";
		}
		else{
			$checked_it ="";
		}
		
		//Show default skin
		if($cf_default_skin==$row_data[skin_dirname]){
			$show_default_skin="<input type=\"radio\" name=\"radio_skin_dirname\" value=\"$row_data[skin_dirname]\" checked=\"checked\" onclick=\"HideDefautl();document.getElementById('default_cell$val').style.backgroundColor='lightgreen';document.getElementById('default_cell$val').style.border='thick solid green'; Editme('index.php?step=$step&what=edit_me_admin_config&table=max_config&edit_id=config_name&edit_id_value=cf_default_skin&edit_key=config_value&edit_value=',this.value,'1',this.value,this.id);\" />";
			$cell_default_style="style=\"border:thick solid green;background-color:lightgreen\" ";
		}
		else{
			$show_default_skin="<input type=\"radio\" name=\"radio_skin_dirname\" value=\"$row_data[skin_dirname]\" onclick=\"HideDefautl();document.getElementById('default_cell$val').style.backgroundColor='lightgreen';document.getElementById('default_cell$val').style.border='thick solid green';Editme('index.php?step=$step&what=edit_me_admin_config&table=max_config&edit_id=config_name&edit_id_value=cf_default_skin&edit_key=config_value&edit_value=',this.value,'1',this.value,this.id);\" />";
			$cell_default_style="";
		}

		//Show delete button
		$show_delete_button="<img onclick=\"document.getElementById('tr$val').style.backgroundColor='#E4E4D3';document.getElementById('bk$val').checked='true';CheckSelected();\" border=\"0\" src=\"html/07_icon_delete.gif\" style=\"cursor:pointer\" alt=\"$skin_tooltip_delete\" title=\"$skin_tooltip_delete\" />";

		$show_list_table .="<tr id=\"tr$val\" style=\"background-color: #EAEAEA;line-height:20px\">\n";
		$show_list_table .="<td width=\"1%\" align=\"center\" id=\"cell$val\" style=\"padding:7px\">$show_icon</td>\n";
		$show_list_table .="<td width=\"7%\" align=\"center\" id=\"default_cell$val\" $cell_default_style>$show_default_skin</td>\n";
		$show_list_table .="<td width=\"*\" style=\"padding:4px;\">$show_title</td>\n";
		$show_list_table .="<td width=\"17%\" style=\"padding:4px;white-space:nowrap\">$show_text_color</td>\n";
		$show_list_table .="<td width=\"20%\">$row_data[skin_dirname]</td>\n";				
		$show_list_table .="<td width=\"1%\" align=\"center\"><input $checked_it type=\"checkbox\" value=\"1\" onclick=\"ShowLoaderImage('$skin_message_updating');if(this.checked){UpdateDataTable('index.php?step=edit_me&table=max_skin&edit_id=skin_id&edit_id_value=$val&edit_key=skin_active&edit_value=1');}else{UpdateDataTable('index.php?step=edit_me&table=max_skin&edit_id=skin_id&edit_id_value=$val&edit_key=skin_active&edit_value=0');}\" /></td>\n";
		$show_list_table .="<td width=\"7%\" align=\"center\" id=\"preview_cell$val\">$show_preview_icon</td>\n";
		$show_list_table .="<td width=\"1%\" align=\"center\" style=\"padding:4px;\">$show_sort</td>\n";
		$show_list_table .="<td width=\"1%\" align=\"center\">$show_delete_button</td>\n";
		$show_list_table .="<td width=\"1%\" align=\"center\"><input onclick=\"if(this.checked){document.getElementById('tr$val').style.backgroundColor='#E4E4D3';}else{document.getElementById('tr$val').style.backgroundColor='#EAEAEA';}\" type=\"checkbox\" id=\"bk$val\" name=\"mylist_id$val\" value=\"$val\" /></td>\n";
		$show_list_table .="</tr>\n";
		$bk_id .="$val,";
		$xrow++;
	}
	if($bk_id{strlen($bk_id)-1} ==",") $bk_id = substr($bk_id, 0, strlen($bk_id)-1);
	set_global_var("bk_id",$bk_id);
	set_global_var("show_list_table",$show_list_table);

	//---------------------------------------------------------------------------------------
	//Print page here
	//Output sample: << 1 | 2 | 3 >>	

	if ($page < 1 || $page=="") 
		$page = 1;
	if ($list_data ==""){
		$display_page_number = "";
	}
	else{
		$display_page_number ="";

		if ($count_list > ($row_per_page)){	
			$c = $count_list / $row_per_page;
			if (gettype($c) =="integer"){
				$b = $c;
			}
			else{
				$b = intval(($count_list / $row_per_page) + 1);
			}				
			
			$display_page_number .="<br /><table class=page_number_table>\n";
			$display_page_number .="    <tr>\n";
			$display_page_number .="      <td width='10%' align=left>{A}</td>\n";
			$display_page_number .="      <td width='33%' align=center>{NUMBER}</td>\n";
			$display_page_number .="      <td width='10%' align=right>{B}</td>\n";
			$display_page_number .="    </tr>\n";
			$display_page_number .="</table>\n";
			
			$count_number =get_page_count_number($page,$b);
			$display_page_number = str_replace("{NUMBER}", $count_number, $display_page_number);
			
			if ($page > 1) {
				$page_pr = $page - 1 ;				
				$dpn ="<a href=\"index.php?step=$step&what=$what&row_number=$row_number&page=$page_pr\"><img border=0 src=html/prv.gif style='vertical-align:middle' title='Page # $page_pr' alt='Page # $page_pr' /></a>";
				$display_page_number = str_replace("{A}", $dpn, $display_page_number);
			}
			else{
				$display_page_number = str_replace("{A}", "<img src=html/prv_disable.gif alt='' style='vertical-align:middle' />", $display_page_number);
			}
			$y=get_global_var("d_num");
			if ($page < $y) {
				$page_ne = $page + 1 ;				
				$display_page_number = str_replace("{B}", "<a href=\"index.php?step=$step&what=$what&row_number=$row_number&page=$page_ne\"><img border=0 src=html/next.gif style='vertical-align:middle' title='Page # $page_ne' alt='Page # $page_ne' /></a>", $display_page_number);
			}	
			else{
				$display_page_number = str_replace("{B}", "<img src=html/next_disable.gif alt='' style='vertical-align:middle' />", $display_page_number);
			}
		}
	}
	set_global_var("display_page_number",$display_page_number);	 
	
	if($db_change =="1"){
		set_global_var("show_info","<span class=\"OK_Message\">$skin_message_mysql_table_skin_updated<br /><br /></span>");	
	}
	else{
		set_global_var("show_info","<span class=\"Error_Message\">$show_info</span>");	
	}
	set_global_var("count_total",$count_list);	
	set_global_var("show_onload_javascript","onkeypress=\"return noGlobalEnterKey(event)\"");
	$skin_txt_upload_by_ftp_guide=str_replace("%skin_folder%","$ecard_root/resource/skin",$skin_txt_upload_by_ftp_guide);
	$skin_txt_upload_by_ftp_guide=str_replace("%url%","index.php?step=$step&page=$page",$skin_txt_upload_by_ftp_guide);
	set_global_var("skin_txt_upload_by_ftp_guide",$skin_txt_upload_by_ftp_guide);
	set_global_var("print_object",get_html_from_layout("admin/html/admin_option_artist.html"));	 
	print_admin_header_footer_page();	

	//--------------------------------------------------------------------------------------
	function get_page_count_number($page,$b){
		global $step,$what,$row_number;
			
		$url="index.php?step=$step&what=$what&row_number=$row_number";
		$count_number ="";
		
		$y=0;
		if ($b <10){
			for($a_num=1; $a_num<=$b; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";					
				}
				else {
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
		}
		elseif(($page > 3) && ($page < ($b-3))){
			for($a_num=1; $a_num<=3; $a_num++) {
				$y++;
				$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
			}
			$count_number .="...";
			for($a_num = $page-1; $a_num<=$page+1; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";
				}
				else {		
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
			$count_number .="...";
			for($a_num = $b-2; $a_num<=$b; $a_num++) {
				$y++;
				$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
			}
		}
		else{
			for($a_num=1; $a_num<=4; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";
				}
				else {
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
			$count_number .="...";			
			for($a_num=$b-3; $a_num<=$b; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";
				}
				else {	
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
		}
		set_global_var("d_num",$b);
		return $count_number;
	}

	//--------------------------------------------------------------------------------------
	function RefreshSortOrder(){
		$list_sort=set_array_from_query("max_skin","skin_id,skin_order","skin_id<>'' Order by skin_order,skin_name_display");
		$xorder=0;
		foreach($list_sort as $array_sort){
			$xorder++;
			update_field_in_db("max_skin","skin_order",$xorder,"skin_id='$array_sort[skin_id]' LIMIT 1");
		}
	}

?>