<?php
/*
+--------------------------------------------------------------------------
|
|	WARNING: REMOVING THIS COPYRIGHT HEADER IS EXPRESSLY FORBIDDEN
|
|   ECardMax Version 10.5
|   ========================================
|   (c) 1999 - 2016 ECARDMAX.COM - All right reserved 
|	Software For Website, Inc.
|   http://www.ecardmax.com 
|   ========================================
|   Email: webmaster@ecardmax.com
|   Purchase Info: http://www.ecardmax.com/purchase/
|   Request Installation: http://ecardmax.com/ehelpmax/
|	
|	WARNING //--------------------------
|
|	Selling the code for this program without prior written consent is expressly forbidden. 
|	This computer program is protected by copyright law. 
|	Unauthorized reproduction or distribution of this program, or any portion of if,
|	may result in severe civil and criminal penalties and will be prosecuted to 
|	the maximum extent possible under the law.
+--------------------------------------------------------------------------
*/	
	if(ECARDMAX!=1)exit;
	if ($admin_login != $crypt_pass){
		//Show login page
		print get_html_from_layout("admin/html/show_login.html");
		exit;
	}	
	
	//Auto add new stamp to database if found
	$list_dir_database=get_dblistvalue("max_stamp","stamp_filename");
	$list_dir=get_list_file("$ecard_root/resource/stamp");
	$db_change ="";
	$stamp_order=1000;
	foreach($list_dir as $dir){
		if (!in_array($dir, $list_dir_database)){
			//Insert new stamp to database
			$stamp_order++;
			$stamp_name_display=str_replace("_"," ",$dir);
			$field_name ="(stamp_name_display,stamp_filename,stamp_order,stamp_user_name_id,stamp_active)";
			$field_value ="('$stamp_name_display','$dir',$stamp_order,'',1)";
			insert_data_to_db("max_stamp",$field_name,$field_value);
			$db_change ="1";
		}
	}

	//Auto remove stamp from mysql if it's not found on server
	foreach($list_dir_database as $dir_mysql){
		if (!in_array($dir_mysql, $list_dir)){
			//Remove from database
			delete_row("max_stamp","stamp_filename='$dir_mysql'");
			$db_change ="1";
		}
	}

	if($db_change=="1")RefreshSortOrder();

	if($what=="add_new"){		
		if (!is_writable("$ecard_root/resource/stamp")){
			$stamp_message_you_mush_chdmod_stamp_folder=str_replace("%stamp_folder%","$ecard_root/resource/stamp",$stamp_message_you_mush_chdmod_stamp_folder);
			$show_info=$stamp_message_you_mush_chdmod_stamp_folder;
		}
		else{			
			$stamp_order=get_dbvalue("max_stamp","count(stamp_id)","stamp_id<>''");
			//Upload image
			$upload_dir ="$ecard_root/resource/stamp";
			for($i=1;$i<=7;$i++){
				$file_key = "file$i";
				$file_name = $POST_FILES[$file_key]['name'];
				$st_caption = str_replace(".gif","",$file_name);
				$st_caption = str_replace(".jpg","",$st_caption);
				$st_caption = str_replace(".png","",$st_caption);
				$st_caption = str_replace("_"," ",$st_caption);
				$st_caption = str_replace("\"","&quot;",$st_caption);				
				$file_upload_name = $upload_dir."/".$file_name;
				
				if($file_name !=""){
					if (!file_exists($file_upload_name)){
						if(move_uploaded_file($POST_FILES[$file_key]['tmp_name'],$file_upload_name)){
							$stamp_order++;
							chmod($file_upload_name,0777);							
							$field_name ="(stamp_name_display,stamp_filename,stamp_active,stamp_order,stamp_user_name_id)";
							$field_value ="('$st_caption','$file_name','1',$stamp_order,'')";
							insert_data_to_db("max_stamp",$field_name,$field_value);
							$stamp_message_stamp_filename_has_been_added=str_replace("%file_name%",$file_name,$stamp_message_stamp_filename_has_been_added);
							$show_info .="<span class=OK_Message>$stamp_message_stamp_filename_has_been_added</span><br />\n";
						}
						else{
							$stamp_message_cannt_upload_filename_please_chmod_folder=str_replace("%file_name%",$file_name,$stamp_message_cannt_upload_filename_please_chmod_folder);
							$show_info .="$stamp_message_cannt_upload_filename_please_chmod_folder<br />\n";
						}
					}
					else{
						$stamp_message_cannt_upload_filename_file_exists=str_replace("%file_name%",$file_name,$stamp_message_cannt_upload_filename_file_exists);
						$show_info .="$stamp_message_cannt_upload_filename_file_exists<br />\n";
					}
				}
			}			
		}		
	}
	elseif($what=="edit_me_admin_config"){
		update_field_in_db("$table","$edit_key",$edit_value,"$edit_id='$edit_id_value' LIMIT 1");
		/*
		//Build file config2.php
		set_global_var_config("max_config");
		$cg ="<?php\n\n\t//DO NOT EDIT THIS FILE. USE ADMIN TO MAKE CHANGE\n\n";
		foreach($http_vars as $key=>$val){		
			if(!(strpos($key,"cf_")===false)){ //if true
				$val=str_replace("\"","&quot;",$val);
				$cg .="\t" . "\$$key = \"$val\"; \n";
			}
		}
		$cg .="?>";
		set_file_content("$ecard_root/config2.php",$cg);
		*/
	}
	elseif($what=="delete_selected"){
		foreach($http_vars as $key=>$val){
			if(!(strpos($key,"mylist_id")===false)){ //if true
				$selected_id =str_replace("mylist_id","",$key);
				//Delete files
				$stamp_filename=get_dbvalue("max_stamp","stamp_filename","stamp_id='$selected_id'");
								
				if (is_writable("$ecard_root/resource/stamp/$stamp_filename")){
					@unlink("$ecard_root/resource/stamp/$stamp_filename");
					$stamp_message_stamp_has_been_removed=str_replace("%stamp_filename%",$stamp_filename,$stamp_message_stamp_has_been_removed);
					$show_info .="<span class=\"OK_Message\">$stamp_message_stamp_has_been_removed</span><br />\n";
				}
				else{
					$stamp_message_cannt_delete_stamp_file_permission_denied=str_replace("%stamp_filename%","$ecard_root/resource/stamp/$stamp_filename",$stamp_message_cannt_delete_stamp_file_permission_denied);
					$show_info .="$stamp_message_cannt_delete_stamp_file_permission_denied<br />\n";
				}

				//Delete row in database
				delete_row("max_stamp","stamp_id='$selected_id' LIMIT 1");
			}
		}
		RefreshSortOrder();
	}
	elseif($what=="set_sort_order"){
		$list_sort=set_array_from_query("max_stamp","stamp_id,stamp_order","stamp_id<>'' Order by stamp_order,stamp_name_display");		
		foreach($list_sort as $array_sort){
			if($current_sort > $sort_number){
				if($array_sort[stamp_order]>=$sort_number){			
					update_field_in_db("max_stamp","stamp_order",$array_sort[stamp_order]+1,"stamp_id='$array_sort[stamp_id]' LIMIT 1");
				}
			}
			else{
				if($array_sort[stamp_order]<=$sort_number){			
					update_field_in_db("max_stamp","stamp_order",$array_sort[stamp_order]-1,"stamp_id='$array_sort[stamp_id]' LIMIT 1");
				}
			}
		}		
		update_field_in_db("max_stamp","stamp_order",$sort_number,"stamp_id='$stamp_id' LIMIT 1");
		
		RefreshSortOrder();
		$what="";
		set_global_var("what","");
	}

	if($row_number =="" || $row_number =="0" || !is_numeric($row_number)) $row_number = 15;
	set_global_var("row_number",$row_number);
	$row_per_page = $row_number;
				
	if ($page < 1 || $page=="") $page =1;
	$start = ($page-1)* 1 * $row_per_page;
	$end = $start + 1 * $row_per_page;

	$list_data =set_array_from_query("max_stamp","*","stamp_user_name_id='' Order by stamp_order,stamp_name_display LIMIT $start,$row_per_page");
	$count_list=get_dbvalue("max_stamp","count(stamp_id)","stamp_user_name_id=''");

	if ($end > $count_list) $end = $count_list;
	$show_list_table="";
	$xrow=0;
	for ($z=$start; $z<$end; $z++) {
		$val = $list_data[$xrow][stamp_id] ;
		$row_data=$list_data[$xrow];

		//Show sort order dropdown menu
		$show_sort="<select size=\"1\" name=\"stamp_order$val\" id=\"stamp_order$val\" onchange=\"location.href='index.php?step=$step&what=set_sort_order&stamp_id=$val&current_sort=$row_data[stamp_order]&sort_number='+this.value;\">";
		for($i=1;$i<=$count_list;$i++){
			if($row_data[stamp_order]==$i){
				$show_sort.="<option value=\"$i\" selected=\"selected\">$i</option>\n";
			}
			else{
				$show_sort.="<option value=\"$i\" >$i</option>\n";
			}
		}
		$show_sort.="</select>";

		//Show icon
		$show_icon ="<img border=\"1\" src=\"$ecard_url/resource/stamp/$row_data[stamp_filename]\" alt=\"\" />";

		//Show title
		$show_title="<input id=\"stamp_name_display$val\" title=\"$stamp_tooltip_click_here_to_rename\" type=\"text\" value=\"$row_data[stamp_name_display]\" style=\"border:0px;background-color:#EAEAEA;cursor:pointer;width:220px;text-decoration:underline;\" onfocus=\"original_value=this.value;this.style.border='1px solid silver';this.style.textDecoration='none';this.style.cursor='text';\" onblur=\"this.style.border='0px';this.style.textDecoration='underline';this.style.cursor='pointer';\" onchange=\"Editme('index.php?step=edit_me&table=max_stamp&edit_id=stamp_id&edit_id_value=$val&edit_key=stamp_name_display&edit_value=',this.value,'1',original_value,this.id);\" />";		
		
	
						
		//Show on/off checkbox
		if($row_data[stamp_active]=="1"){
			$checked_it ="checked=\"checked\"";
		}
		else{
			$checked_it ="";
		}

		
		//Show default stamp
		if($cf_default_stamp==$row_data[stamp_filename]){
			$show_default_stamp="<input type=\"radio\" name=\"radio_stamp_filename\" value=\"$row_data[stamp_filename]\" checked=\"checked\" onclick=\"HideDefautl();document.getElementById('default_cell$val').style.backgroundColor='lightgreen';document.getElementById('default_cell$val').style.border='thick solid green'; Editme('index.php?step=$step&what=edit_me_admin_config&table=max_config&edit_id=config_name&edit_id_value=cf_default_stamp&edit_key=config_value&edit_value=',this.value,'1',this.value,this.id);\" />";
			$cell_default_style="style=\"border:thick solid green;background-color:lightgreen\" ";
		}
		else{
			$show_default_stamp="<input type=\"radio\" name=\"radio_stamp_filename\" value=\"$row_data[stamp_filename]\" onclick=\"HideDefautl();document.getElementById('default_cell$val').style.backgroundColor='lightgreen';document.getElementById('default_cell$val').style.border='thick solid green';Editme('index.php?step=$step&what=edit_me_admin_config&table=max_config&edit_id=config_name&edit_id_value=cf_default_stamp&edit_key=config_value&edit_value=',this.value,'1',this.value,this.id);\" />";
			$cell_default_style="";
		}

		//Show delete button
		$show_delete_button="<img onclick=\"document.getElementById('tr$val').style.backgroundColor='#E4E4D3';document.getElementById('bk$val').checked='true';CheckSelected();\" border=\"0\" src=\"html/07_icon_delete.gif\" style=\"cursor:pointer\" alt=\"$stamp_tooltip_delete\" title=\"$stamp_tooltip_delete\" />";
			
		$show_list_table .="<tr id=\"tr$val\" style=\"background-color: #EAEAEA;line-height:20px\">\n";
		$show_list_table .="<td width=\"1%\" align=\"center\" id=\"cell$val\" style=\"padding:7px\">$show_icon</td>\n";
		$show_list_table .="<td width=\"7%\" align=\"center\" id=\"default_cell$val\" $cell_default_style>$show_default_stamp</td>\n";
		$show_list_table .="<td width=\"*\" style=\"padding:4px;\">$show_title</td>\n";
		$show_list_table .="<td width=\"20%\">$row_data[stamp_filename]</td>\n";		
		$show_list_table .="<td width=\"12%\" align=\"center\"><input $checked_it type=\"checkbox\" value=\"1\" 
		
		onclick=\"ShowLoaderImage('$stamp_message_updating');if(this.checked){UpdateDataTable('index.php?step=edit_me&table=max_stamp&edit_id=stamp_id&edit_id_value=$val&edit_key=stamp_active&edit_value=1');}else{UpdateDataTable('index.php?step=edit_me&table=max_stamp&edit_id=stamp_id&edit_id_value=$val&edit_key=stamp_active&edit_value=0');}\" /></td>\n";
		
		
		
		$show_list_table .="<td width=\"1%\" align=\"center\" style=\"padding:4px;\">$show_sort</td>\n";
		$show_list_table .="<td width=\"1%\" align=\"center\">$show_delete_button</td>\n";
		$show_list_table .="<td width=\"1%\" align=\"center\"><input onclick=\"if(this.checked){document.getElementById('tr$val').style.backgroundColor='#E4E4D3';}else{document.getElementById('tr$val').style.backgroundColor='#EAEAEA';}\" type=\"checkbox\" id=\"bk$val\" name=\"mylist_id$val\" value=\"$val\" /></td>\n";
		$show_list_table .="</tr>\n";
		$bk_id .="$val,";
		$xrow++;
	}
	if($bk_id{strlen($bk_id)-1} ==",") $bk_id = substr($bk_id, 0, strlen($bk_id)-1);
	set_global_var("bk_id",$bk_id);
	set_global_var("show_list_table",$show_list_table);

	//---------------------------------------------------------------------------------------
	//Print page here
	//Output sample: << 1 | 2 | 3 >>	

	if ($page < 1 || $page=="") 
		$page = 1;
	if ($list_data ==""){
		$display_page_number = "";
	}
	else{
		$display_page_number ="";

		if ($count_list > ($row_per_page)){	
			$c = $count_list / $row_per_page;
			if (gettype($c) =="integer"){
				$b = $c;
			}
			else{
				$b = intval(($count_list / $row_per_page) + 1);
			}				
			
			$display_page_number .="<br /><table class=page_number_table>\n";
			$display_page_number .="    <tr>\n";
			$display_page_number .="      <td width='10%' align=left>{A}</td>\n";
			$display_page_number .="      <td width='33%' align=center>{NUMBER}</td>\n";
			$display_page_number .="      <td width='10%' align=right>{B}</td>\n";
			$display_page_number .="    </tr>\n";
			$display_page_number .="</table>\n";
			
			$count_number =get_page_count_number($page,$b);
			$display_page_number = str_replace("{NUMBER}", $count_number, $display_page_number);
			
			if ($page > 1) {
				$page_pr = $page - 1 ;				
				$dpn ="<a href=\"index.php?step=$step&row_number=$row_number&page=$page_pr\"><img border=0 src=html/prv.gif style='vertical-align:middle' title='Page # $page_pr' alt='Page # $page_pr' /></a>";
				$display_page_number = str_replace("{A}", $dpn, $display_page_number);
			}
			else{
				$display_page_number = str_replace("{A}", "<img src=html/prv_disable.gif alt='' style='vertical-align:middle' />", $display_page_number);
			}
			$y=get_global_var("d_num");
			if ($page < $y) {
				$page_ne = $page + 1 ;				
				$display_page_number = str_replace("{B}", "<a href=\"index.php?step=$step&row_number=$row_number&page=$page_ne\"><img border=0 src=html/next.gif style='vertical-align:middle' title='Page # $page_ne' alt='Page # $page_ne' /></a>", $display_page_number);
			}	
			else{
				$display_page_number = str_replace("{B}", "<img src=html/next_disable.gif alt='' style='vertical-align:middle' />", $display_page_number);
			}
		}
	}
	set_global_var("display_page_number",$display_page_number);	 
	
	if($db_change =="1"){
		set_global_var("show_info","<span class=\"OK_Message\">Mysql table Stamp has been updated<br /><br /></span>");	
	}
	else{
		set_global_var("show_info","<span class=\"Error_Message\">$show_info<br /></span>");	
	}
	set_global_var("count_total",$count_list);	
	set_global_var("show_onload_javascript","onkeypress=\"return noGlobalEnterKey(event)\"");
	$stamp_txt_how_to_add_new_stamp_by_ftp_tip=str_replace("%stamp_folder%","$ecard_root/resource/stamp",$stamp_txt_how_to_add_new_stamp_by_ftp_tip);
	$stamp_txt_how_to_add_new_stamp_by_ftp_tip=str_replace("%url%","index.php?step=$step&page=$page",$stamp_txt_how_to_add_new_stamp_by_ftp_tip);
	set_global_var("stamp_txt_how_to_add_new_stamp_by_ftp_tip",$stamp_txt_how_to_add_new_stamp_by_ftp_tip);
	set_global_var("print_object",get_html_from_layout("admin/html/admin_option_stamp.html"));	
	print_admin_header_footer_page();	

	//--------------------------------------------------------------------------------------
	function get_page_count_number($page,$b){
		global $step,$what,$row_number;
			
		$url="index.php?step=$step&row_number=$row_number";
		$count_number ="";
		
		$y=0;
		if ($b <10){
			for($a_num=1; $a_num<=$b; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";					
				}
				else {
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
		}
		elseif(($page > 3) && ($page < ($b-3))){
			for($a_num=1; $a_num<=3; $a_num++) {
				$y++;
				$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
			}
			$count_number .="...";
			for($a_num = $page-1; $a_num<=$page+1; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";
				}
				else {		
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
			$count_number .="...";
			for($a_num = $b-2; $a_num<=$b; $a_num++) {
				$y++;
				$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
			}
		}
		else{
			for($a_num=1; $a_num<=4; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";
				}
				else {
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
			$count_number .="...";			
			for($a_num=$b-3; $a_num<=$b; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";
				}
				else {	
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
		}
		set_global_var("d_num",$b);
		return $count_number;
	}

	//--------------------------------------------------------------------------------------
	function RefreshSortOrder(){
		$list_sort=set_array_from_query("max_stamp","stamp_id,stamp_order","stamp_id<>'' Order by stamp_order,stamp_name_display");
		$xorder=0;
		foreach($list_sort as $array_sort){
			$xorder++;
			update_field_in_db("max_stamp","stamp_order",$xorder,"stamp_id='$array_sort[stamp_id]' LIMIT 1");
		}
	}

?>