<?php
/*
+--------------------------------------------------------------------------
|
|	WARNING: REMOVING THIS COPYRIGHT HEADER IS EXPRESSLY FORBIDDEN
|
|   ECardMax Version 10.5
|   ========================================
|   (c) 1999 - 2016 ECARDMAX.COM - All right reserved 
|	Software For Website, Inc.
|   http://www.ecardmax.com 
|   ========================================
|   Email: webmaster@ecardmax.com
|   Purchase Info: http://www.ecardmax.com/purchase/
|   Request Installation: http://ecardmax.com/ehelpmax/
|	
|	WARNING //--------------------------
|
|	Selling the code for this program without prior written consent is expressly forbidden. 
|	This computer program is protected by copyright law. 
|	Unauthorized reproduction or distribution of this program, or any portion of if,
|	may result in severe civil and criminal penalties and will be prosecuted to 
|	the maximum extent possible under the law.
+--------------------------------------------------------------------------
*/	
	if(ECARDMAX!=1)exit;
	if ($admin_login != $crypt_pass){
		//Show login page
		print get_html_from_layout("admin/html/show_login.html");
		exit;
	}

	if($what=="add_new"){
        $upload_to = "$ecard_root/resource/picture/Artist";
        if(!file_exists($upload_to)) {
            mkdir ($upload_to, 0777);
            chmod ($upload_to, 0777);
        }

		if (!is_writable("$ecard_root/resource/picture/Artist")){
			$skin_message_you_must_chmod_this_folder=str_replace("%skin_folder%","$ecard_root/resource/picture/Artist",$skin_message_you_must_chmod_this_folder);
			$show_info="$skin_message_you_must_chmod_this_folder";
		}
		else{

			if (file_exists($upload_to)){
				//Upload image
                $file_upload_name = $POST_FILES['artist_picture']['name'];
                move_uploaded_file($POST_FILES['artist_picture']['tmp_name'], "$upload_to/$file_upload_name");
                chmod("$upload_to/$file_upload_name",0777);


				//Insert to database table max_skin
				$field_name ="(user_name, user_picture, user_website, user_description)";
				$field_value ="('$artist_name', '$file_upload_name', '$artist_website', '$mmess_body')";
				insert_data_to_db("max_artist", $field_name, $field_value);
				$skin_name_display = stripslashes($artist_name);
				$skin_message_skin_has_been_added=str_replace("%skin_name_display%",$skin_name_display,$skin_message_skin_has_been_added);
				$show_info ="<span class=OK_Message>Artist name $skin_name_display has been added</span><br />\n";
			}
		}		
	}
	elseif($what=="edit_me_admin_config"){
		update_field_in_db("$table","$edit_key",$edit_value,"$edit_id='$edit_id_value' LIMIT 1");
		/*
		//Build file config2.php
		set_global_var_config("max_config");
		$cg ="<?php\n\n\t//DO NOT EDIT THIS FILE. USE ADMIN TO MAKE CHANGE\n\n";
		foreach($http_vars as $key=>$val){		
			if(!(strpos($key,"cf_")===false)){ //if true
				$val=str_replace("\"","&quot;",$val);
				$cg .="\t" . "\$$key = \"$val\"; \n";
			}
		}
		$cg .="?>";
		set_file_content("$ecard_root/config2.php",$cg);
		*/
	}
	elseif($what=="delete_selected"){
		foreach($http_vars as $key=>$val){
			if(!(strpos($key,"mylist_id")===false)){ //if true
				$selected_id =str_replace("mylist_id","",$key);
				//Delete files & folder
				$user_picture=get_dbvalue("max_artist","user_picture","user_id='$selected_id'");
								
				if (is_writable("$ecard_root/resource/picture/Artist")){
					$array=get_list_file("$ecard_root/resource/picture/Artist/$user_picture");
					$wrong="";

                    if (is_writable("$ecard_root/resource/picture/Artist/$user_picture")){
                        @unlink("$ecard_root/resource/picture/Artist/$user_picture");
                    }
                    else{
                        $wrong = 1;
                        $skin_message_cannt_delete_file_permission_denied=str_replace("%file%","$ecard_root/resource/picture/Artist/$user_picture",$skin_message_cannt_delete_file_permission_denied);
                        $show_info .="$skin_message_cannt_delete_file_permission_denied<br />\n";
                    }

					if($wrong ==""){
						@rmdir("$ecard_root/resource/picture/Artist/$user_picture");
						$skin_message_skin_has_been_removed=str_replace("%skin_dirname%","$skin_dirname",$skin_message_skin_has_been_removed);
						$show_info .="<span class=\"OK_Message\">$skin_message_skin_has_been_removed</span><br />\n";
					}
					else{
						$skin_message_cannt_delete_folder_skin_permission_denied=str_replace("%skin_dirname%","$ecard_root/resource/picture/Artist",$skin_message_cannt_delete_folder_skin_permission_denied);
						$show_info .="$skin_message_cannt_delete_folder_skin_permission_denied<br />\n";
					}
				}
				else{
					$skin_message_cannt_delete_folder_skin_permission_denied=str_replace("%skin_dirname%","$ecard_root/resource/picture/Artist",$skin_message_cannt_delete_folder_skin_permission_denied);
					$show_info .="$skin_message_cannt_delete_folder_skin_permission_denied<br />\n";
				}

				//Delete row in database
				delete_row("max_artist","user_id='$selected_id' LIMIT 1");
			}
		}
	}
	elseif($what=="set_sort_order"){
		$list_sort=set_array_from_query("max_skin","skin_id,skin_order","skin_id<>'' Order by skin_order,skin_name_display");		
		foreach($list_sort as $array_sort){
			if($current_sort > $sort_number){
				if($array_sort[skin_order]>=$sort_number){			
					update_field_in_db("max_skin","skin_order",$array_sort[skin_order]+1,"skin_id='$array_sort[skin_id]' LIMIT 1");
				}
			}
			else{
				if($array_sort[skin_order]<=$sort_number){			
					update_field_in_db("max_skin","skin_order",$array_sort[skin_order]-1,"skin_id='$array_sort[skin_id]' LIMIT 1");
				}
			}
		}		
		update_field_in_db("max_skin","skin_order",$sort_number,"skin_id='$skin_id' LIMIT 1");
        
		$what="";
		set_global_var("what","");
	}

	if($row_number =="" || $row_number =="0" || !is_numeric($row_number)) $row_number = 15;
	set_global_var("row_number",$row_number);
	$row_per_page = $row_number;
				
	if ($page < 1 || $page=="") $page =1;
	$start = ($page-1)* 1 * $row_per_page;
	$end = $start + 1 * $row_per_page;

	$list_data =set_array_from_query("max_artist","*","user_id<>'' Order by user_name LIMIT $start,$row_per_page");
	$count_list=get_dbvalue("max_artist","count(user_id)");

	if ($end > $count_list) $end = $count_list;
	$show_list_table="";
	$xrow=0;
	for ($z=$start; $z<$end; $z++) {
		$val = $list_data[$xrow][user_id] ;
		$row_data=$list_data[$xrow];

		//Show icon
		if(file_exists("$ecard_root/resource/picture/Artist/$row_data[user_picture]")){
			$show_icon ="<img border=\"1\" width='100px' src=\"$ecard_url/resource/picture/Artist/$row_data[user_picture]\" alt=\"\" />";
		}
		else{
			$show_icon ="<div style=\"border:1px solid black;background-color:red;width:73px;height:84px;text-align:center;color:yellow;font-weight:bold\">$skin_txt_no_icon</div>";
		}

		//Show title
		$show_title="<input id=\"skin_name_display$val\" title=\"$skin_tooltip_click_here_to_rename\" type=\"text\" value=\"$row_data[user_name]\" style=\"border:0px;background-color:#EAEAEA;cursor:pointer;width:220px;text-decoration:underline;\" onfocus=\"original_value=this.value;this.style.border='1px solid silver';this.style.textDecoration='none';this.style.cursor='text';\" onblur=\"this.style.border='0px';this.style.textDecoration='underline';this.style.cursor='pointer';\" onchange=\"Editme('index.php?step=edit_me&table=max_artist&edit_id=user_id&edit_id_value=$val&edit_key=user_name&edit_value=',this.value,'1',original_value,this.id);\" />";

        //Show Website
        $show_website ="<input id=\"website_name_display$val\" title=\"$skin_tooltip_click_here_to_rename\" type=\"text\" value=\"$row_data[user_website]\" style=\"border:0px;background-color:#EAEAEA;cursor:pointer;width:220px;text-decoration:underline;\" onfocus=\"original_value=this.value;this.style.border='1px solid silver';this.style.textDecoration='none';this.style.cursor='text';\" onblur=\"this.style.border='0px';this.style.textDecoration='underline';this.style.cursor='pointer';\" onchange=\"Editme('index.php?step=edit_me&table=max_artist&edit_id=user_id&edit_id_value=$val&edit_key=user_website&edit_value=',this.value,'1',original_value,this.id);\" />";

		//Show delete button
		$show_delete_button="<img onclick=\"document.getElementById('tr$val').style.backgroundColor='#E4E4D3';document.getElementById('bk$val').checked='true';CheckSelected();\" border=\"0\" src=\"html/07_icon_delete.gif\" style=\"cursor:pointer\" alt=\"$skin_tooltip_delete\" title=\"$skin_tooltip_delete\" />";

		$show_list_table .="<tr id=\"tr$val\" style=\"background-color: #EAEAEA;line-height:20px\">\n";
		$show_list_table .="<td width=\"1%\" align=\"center\" id=\"cell$val\" style=\"padding:7px\">$show_icon</td>\n";
		$show_list_table .="<td width=\"*\" style=\"padding:4px;\">$show_title</td>\n";
		$show_list_table .="<td width=\"17%\" style=\"padding:4px;white-space:nowrap\">$show_website</td>\n";
		$show_list_table .="<td width=\"20%\">$row_data[user_description]</td>\n";
		$show_list_table .="<td width=\"1%\" align=\"center\">$show_delete_button</td>\n";
		$show_list_table .="<td width=\"1%\" align=\"center\"><input onclick=\"if(this.checked){document.getElementById('tr$val').style.backgroundColor='#E4E4D3';}else{document.getElementById('tr$val').style.backgroundColor='#EAEAEA';}\" type=\"checkbox\" id=\"bk$val\" name=\"mylist_id$val\" value=\"$val\" /></td>\n";
		$show_list_table .="</tr>\n";
		$bk_id .="$val,";
		$xrow++;
	}
	if($bk_id{strlen($bk_id)-1} ==",") $bk_id = substr($bk_id, 0, strlen($bk_id)-1);
	set_global_var("bk_id",$bk_id);
	set_global_var("show_list_table",$show_list_table);

	//---------------------------------------------------------------------------------------
	//Print page here
	//Output sample: << 1 | 2 | 3 >>	

	if ($page < 1 || $page=="") 
		$page = 1;
	if ($list_data ==""){
		$display_page_number = "";
	}
	else{
		$display_page_number ="";

		if ($count_list > ($row_per_page)){	
			$c = $count_list / $row_per_page;
			if (gettype($c) =="integer"){
				$b = $c;
			}
			else{
				$b = intval(($count_list / $row_per_page) + 1);
			}				
			
			$display_page_number .="<br /><table class=page_number_table>\n";
			$display_page_number .="    <tr>\n";
			$display_page_number .="      <td width='10%' align=left>{A}</td>\n";
			$display_page_number .="      <td width='33%' align=center>{NUMBER}</td>\n";
			$display_page_number .="      <td width='10%' align=right>{B}</td>\n";
			$display_page_number .="    </tr>\n";
			$display_page_number .="</table>\n";
			
			$count_number =get_page_count_number($page,$b);
			$display_page_number = str_replace("{NUMBER}", $count_number, $display_page_number);
			
			if ($page > 1) {
				$page_pr = $page - 1 ;				
				$dpn ="<a href=\"index.php?step=$step&what=$what&row_number=$row_number&page=$page_pr\"><img border=0 src=html/prv.gif style='vertical-align:middle' title='Page # $page_pr' alt='Page # $page_pr' /></a>";
				$display_page_number = str_replace("{A}", $dpn, $display_page_number);
			}
			else{
				$display_page_number = str_replace("{A}", "<img src=html/prv_disable.gif alt='' style='vertical-align:middle' />", $display_page_number);
			}
			$y=get_global_var("d_num");
			if ($page < $y) {
				$page_ne = $page + 1 ;				
				$display_page_number = str_replace("{B}", "<a href=\"index.php?step=$step&what=$what&row_number=$row_number&page=$page_ne\"><img border=0 src=html/next.gif style='vertical-align:middle' title='Page # $page_ne' alt='Page # $page_ne' /></a>", $display_page_number);
			}	
			else{
				$display_page_number = str_replace("{B}", "<img src=html/next_disable.gif alt='' style='vertical-align:middle' />", $display_page_number);
			}
		}
	}
	set_global_var("display_page_number",$display_page_number);	 
	
	if($db_change =="1"){
		set_global_var("show_info","<span class=\"OK_Message\">$skin_message_mysql_table_skin_updated<br /><br /></span>");	
	}
	else{
		set_global_var("show_info","<span class=\"Error_Message\">$show_info</span>");	
	}
	set_global_var("count_total",$count_list);	
	set_global_var("show_onload_javascript","onkeypress=\"return noGlobalEnterKey(event)\"");
	$skin_txt_upload_by_ftp_guide=str_replace("%skin_folder%","$ecard_root/resource/skin",$skin_txt_upload_by_ftp_guide);
	$skin_txt_upload_by_ftp_guide=str_replace("%url%","index.php?step=$step&page=$page",$skin_txt_upload_by_ftp_guide);
	set_global_var("skin_txt_upload_by_ftp_guide",$skin_txt_upload_by_ftp_guide);
	set_global_var("print_object",get_html_from_layout("admin/html/admin_option_artist.html"));	 
	print_admin_header_footer_page();	

	//--------------------------------------------------------------------------------------
	function get_page_count_number($page,$b){
		global $step,$what,$row_number;
			
		$url="index.php?step=$step&what=$what&row_number=$row_number";
		$count_number ="";
		
		$y=0;
		if ($b <10){
			for($a_num=1; $a_num<=$b; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";					
				}
				else {
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
		}
		elseif(($page > 3) && ($page < ($b-3))){
			for($a_num=1; $a_num<=3; $a_num++) {
				$y++;
				$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
			}
			$count_number .="...";
			for($a_num = $page-1; $a_num<=$page+1; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";
				}
				else {		
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
			$count_number .="...";
			for($a_num = $b-2; $a_num<=$b; $a_num++) {
				$y++;
				$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
			}
		}
		else{
			for($a_num=1; $a_num<=4; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";
				}
				else {
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
			$count_number .="...";			
			for($a_num=$b-3; $a_num<=$b; $a_num++) {
				$y++;
				if ($a_num == $page) {
					$count_number .="<span style=\"cursor: default;\" class='page_active'>$a_num</span>";
				}
				else {	
					$count_number .="<a class=\"page_other\" href=\"$url&page=$a_num\">$a_num</a>";
				}
			}
		}
		set_global_var("d_num",$b);
		return $count_number;
	}

?>